# WARNING: this file is not suitable for production, please use with caution
version: '3'

volumes:
  todo_db_vol:

services:
  postgres:
    image: postgres:12
    volumes:
      - todo_db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=todo_db
    ports:
      - "8471:5432"
    restart: always
  web:
    image: todo_service_api
    build: .
    command: uwsgi --http 0.0.0.0:5000 --module todo_service_api.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=postgresql://postgres:admin123@postgres:5432/todo_db
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND_URL=redis://redis
    volumes:
      - ./todo_service_api:/code/todo_service_api
      - ./db/:/db/
    ports:
      - "5000:5000"
  redis:
    image: redis
  celery:
    image: todo_service_api
    command: "celery -A todo_service_api.celery_app:app worker -l info"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - web
    environment:
      - DATABASE_URI=postgresql://postgres:admin123@postgres:5432/todo_db
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND_URL=redis://redis
      - MAIL_SERVER=smtp.mail.ru
      - MAIL_PORT=465
      - MAIL_USERNAME=***
      - MAIL_PASSWORD=***
